// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7BZxpR6PnLcczeiqclusdTSAydsdL4JU',
    appId: '1:418205475908:web:0ccc9740a9c9007eee8811',
    messagingSenderId: '418205475908',
    projectId: 'food-kiosk-398e7',
    authDomain: 'food-kiosk-398e7.firebaseapp.com',
    storageBucket: 'food-kiosk-398e7.appspot.com',
    measurementId: 'G-DDHW0BKZGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG6me6I24_ES4W255WG16DquunUYkaEcE',
    appId: '1:418205475908:android:dd2388c90cffd8ffee8811',
    messagingSenderId: '418205475908',
    projectId: 'food-kiosk-398e7',
    storageBucket: 'food-kiosk-398e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnkeT0iuVfPkiQdHB9hkz4KZMekMqPJ_k',
    appId: '1:418205475908:ios:dfd13ff11ce46a73ee8811',
    messagingSenderId: '418205475908',
    projectId: 'food-kiosk-398e7',
    storageBucket: 'food-kiosk-398e7.appspot.com',
    iosBundleId: 'com.example.kioskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnkeT0iuVfPkiQdHB9hkz4KZMekMqPJ_k',
    appId: '1:418205475908:ios:070207ce04eff72eee8811',
    messagingSenderId: '418205475908',
    projectId: 'food-kiosk-398e7',
    storageBucket: 'food-kiosk-398e7.appspot.com',
    iosBundleId: 'com.example.kioskApp.RunnerTests',
  );
}
